//
export enum Topics {
  RUN_COMMAND = 'RUN_COMMAND',
  STDOUT_STREAM = 'STDOUT_STREAM',
  STDOUT_EXIT = 'STDOUT_EXIT',
  QUERY = 'QUERY',
  RUN_VALIDATOR = 'RUN_VALIDATOR',
  KILL_VALIDATOR = 'KILL_VALIDATOR',
  IS_VALIDATOR_RUNNING = 'IS_VALIDATOR_RUNNING',
  VALIDATOR = 'VALIDATOR',
  STATUS ='STATUS'
}
