//
export enum Topics {
  RUN_COMMAND = 'RUN_COMMAND',
  STDOUT_STREAM = 'STDOUT_STREAM',
  STDOUT_EXIT = 'STDOUT_EXIT',
  QUERY = 'QUERY',
  RUN_VALIDATOR = 'RUN_VALIDATOR',
  KILL_VALIDATOR = 'KILL_VALIDATOR',
  IS_VALIDATOR_RUNNING = 'IS_VALIDATOR_RUNNING',
  VALIDATOR = 'VALIDATOR',
  STATUS = 'STATUS',
  SAVEDSTORE = 'SAVEDSTORE',
  UPDATE = 'UPDATE',
  OPEN_FOLDER = 'OPEN_FOLDER',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  SETTINGS = 'SETTINGS',
  SELECT_FOLDER = 'SELECT_FOLDER',
  CREATE_PROGRAM = 'CREATE_PROGRAM',
  CODE = 'CODE',
  GET_PROGRAM_DETAILS = 'GET_PROGRAM_DETAILS',
  DELETE_PROGRAM = 'DELETE_PROGRAM',
  GET_ACCOUNT_DETAILS = 'GET_ACCOUNT_DETAILS',
  AIRDROP = 'AIRDROP'
}
